DoctorToothieApp/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoctorToothieApp.Persistence;
using DoctorToothieApp.Persistence.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace DoctorToothieApp.Controllers
{
    [Authorize(Roles = "Admin")]

    public class LocationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LocationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Locations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Locations.Include("Rooms").ToListAsync());
        }

        // GET: Locations/Details/5

        // GET: Locations/Create
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address")] Location location)
        {
            if (ModelState.IsValid)
            {
                _context.Add(location);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Locations.FindAsync(id);
            if (location == null)
            {
                return NotFound();
            }
            return View(location);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address")] Location location)
        {
            if (id != location.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(location);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationExists(location.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(location);
        }

        public async Task<IActionResult> Remove(int id)
        {

            var location = await _context.Locations.FindAsync(id);
            if (location != null)
            {
                _context.Locations.Remove(location);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        private bool LocationExists(int id)
        {
            return _context.Locations.Any(e => e.Id == id);
        }
        [HttpPost]
        public IActionResult DeleteRoom(int id)
        {
            var room = _context.Rooms.Find(id);
            if (room != null)
            {
                _context.Rooms.Remove(room);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult AddRoom(int LocationId, string Number)
        {
            if (!string.IsNullOrWhiteSpace(Number))
            {
                var room = new Room
                {
                    Number = Number,
                    ParentId = LocationId
                };
                _context.Rooms.Add(room);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

DoctorToothieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - Doctor Toothie</title>

    <!-- Bootstrap CSS -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap-reboot.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap-utilities.min.css" rel="stylesheet" />

    <!-- Custom styles -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DoctorToothieApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom shadow-sm mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Doctor Toothie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                        @if (User?.IsInRole("User") == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Reserve" asp-action="Index">Rezerwacje</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Children" asp-action="Index">Rodzina</a>
                            </li>
                        }
                        @if (User?.IsInRole("Doctor") == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Appointments" asp-action="Index">Wizyty</a>
                            </li>
                        }
                        @if (User?.IsInRole("Admin") == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Doctors" asp-action="Index">Doktorzy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Roles" asp-action="Index">Role</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Procedures" asp-action="Index">Procedury</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Locations" asp-action="Index">Lokacje</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-4">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-muted py-3 mt-auto">
        <div class="container text-center">
            &copy; 2024 - DoctorToothieApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Polityka prywatności</a>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>